package rules

import (
	"regexp"
	"strings"

	"blink/internal/token"
	"blink/internal/tokens"
)

// Symplify: https://github.com/symplify/coding-standard/blob/main/src/Fixer/Commenting/RemoveUselessDefaultCommentFixer.php
//
// RemoveUselessDefaultComment removes IDE-generated boilerplate comments
// ("// TODO: Implement x() method.", "Class Foo" docblocks, "constructor.", ...).
type RemoveUselessDefaultComment struct{}

func (RemoveUselessDefaultComment) Name() string {
	return `Symplify\CodingStandard\Fixer\Commenting\RemoveUselessDefaultCommentFixer`
}

func (RemoveUselessDefaultComment) SourceURL() string {
	return "https://github.com/symplify/coding-standard/blob/main/src/Fixer/Commenting/RemoveUselessDefaultCommentFixer.php"
}

var uselessCommentRegexes = []*regexp.Regexp{
	regexp.MustCompile(`// TODO: Change the autogenerated stub$`),
	regexp.MustCompile(`// TODO: Implement .*\(\) method.$`),
	regexp.MustCompile(`(?i)^(//|(\s|\*)+)(\s\w+\s)?constructor(\.)?$`),
	regexp.MustCompile(`(?i)\s\*\sClass\s+representing\s+(\w+)$`),
	regexp.MustCompile(`(/\*\*\s+)\*\s+[cC]lass\s+[^\s]*(\s+\*/)$`),
	regexp.MustCompile(`(?i)//\s+(class|trait|interface)\s+\w+$`),
	regexp.MustCompile(`(?i)\s\*\s(class|trait|interface)\s+(\w)+$`),
}

var doctrineGeneratedRegex = regexp.MustCompile(`(?i)^(/\*{2}\s+?)?(\*|//)\s+This class was generated by the Doctrine ORM\. Add your own custom\r?\n\s+\*\s+repository methods below\.(\s+\*/)$`)

// matches a heredoc/nowdoc opener at end of line, capturing the closing label
var heredocOpenerRegex = regexp.MustCompile(`<<<[ \t]*['"]?([A-Za-z_\x80-\xff][A-Za-z0-9_\x80-\xff]*)['"]?[ \t]*\r?$`)

func (RemoveUselessDefaultComment) Fix(s *tokens.Stream) bool {
	className := firstClassLikeName(s)
	changed := false
	for i := 0; i < s.Len(); i++ {
		if s.At(i).Kind != token.Comment && s.At(i).Kind != token.DocComment {
			continue
		}
		original := s.At(i).Value
		cleaned := clearUselessDocContent(original, className)
		if cleaned == "" {
			s.RemoveAt(i)
			i--
			changed = true
		} else if cleaned != original {
			s.SetValue(i, cleaned)
			changed = true
		}
	}
	return changed
}

func firstClassLikeName(s *tokens.Stream) string {
	for i := 0; i < s.Len(); i++ {
		if s.At(i).Kind == token.Keyword && isClassLikeKeyword(strings.ToLower(s.At(i).Value)) {
			if n := nextSignificantIndex(s, i); n >= 0 && s.At(n).Kind == token.Ident {
				return s.At(n).Value
			}
		}
	}
	return ""
}

func clearUselessDocContent(docContent, className string) string {
	lines := strings.Split(docContent, "\n")
	kept := make([]string, 0, len(lines))
	inHeredoc := false
	var heredocLabel string
	for _, line := range lines {
		// heredoc/nowdoc bodies are opaque string content: keep every line verbatim
		if inHeredoc {
			kept = append(kept, line)
			if isHeredocCloser(line, heredocLabel) {
				inHeredoc = false
			}
			continue
		}
		if match := heredocOpenerRegex.FindStringSubmatch(line); match != nil {
			heredocLabel = match[1]
			inHeredoc = true
			kept = append(kept, line)
			continue
		}
		if className != "" && strings.Trim(line, "* ") == className {
			continue
		}
		for _, re := range uselessCommentRegexes {
			line = re.ReplaceAllString(line, "")
		}
		if line == "" {
			continue
		}
		kept = append(kept, line)
	}
	if len(kept) == 2 && kept[0] == "/**" && strings.TrimSpace(kept[1]) == "*/" {
		return ""
	}
	commentText := strings.Join(kept, "\n")
	return doctrineGeneratedRegex.ReplaceAllString(commentText, "")
}

func isHeredocCloser(line, label string) bool {
	trimmed := strings.TrimLeft(line, " \t")
	if !strings.HasPrefix(trimmed, label) {
		return false
	}
	after := trimmed[len(label):]
	return after == "" || !isIdentByte(after[0])
}
