# inspired by https://github.com/rectorphp/rector-src/blob/main/.github/workflows/build_scoped_rector.yaml
name: Build Release

on:
    push:
        branches:
            - main
        tags:
            - '*'

jobs:
    build_release:
        runs-on: ubuntu-latest

        steps:
            -   uses: "actions/checkout@v4"
                with:
                    token: ${{ secrets.ACCESS_TOKEN }}

            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.3
                    coverage: none

            # invoke patches
            -   run: composer install

            # but no dev packages
            -   run: composer update --no-dev

            # remove code-sniffer tests
            -   run: |
                    rm -rf vendor/phpcsstandards/php_codesniffer/tests/
                    rm -rf vendor/phpcsstandards/php_codesniffer/src/Standards/*/Tests/
                    rm -rf vendor/phpcsstandards/php_codesniffer/src/Standards/*/Docs/

                    # remove tests and useless files, to make downgraded, scoped and deployed codebase as small as possible
                    rm -rf vendor/phpcsstandards/php_codesniffer/src/Reports vendor/phpcsstandards/php_codesniffer/src/Filters vendor/phpcsstandards/php_codesniffer/src/Generators vendor/friendsofphp/php-cs-fixer/src/Linter vendor/friendsofphp/php-cs-fixer/src/Runner vendor/friendsofphp/php-cs-fixer/src/Documentation vendor/friendsofphp/php-cs-fixer/src/Cache vendor/friendsofphp/php-cs-fixer/src/Console/Output vendor/friendsofphp/php-cs-fixer/src/Console/Report vendor/friendsofphp/php-cs-fixer/src/Console/SelfUpdate vendor/friendsofphp/php-cs-fixer/src/Console/Command/DescribeCommand.php vendor/friendsofphp/php-cs-fixer/src/Console/Command/Documentation.php vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php vendor/friendsofphp/php-cs-fixer/src/Console/Command/HelpCommand.php vendor/friendsofphp/php-cs-fixer/src/Console/Command/ListSetsCommand.php vendor/friendsofphp/php-cs-fixer/src/Console/Command/SelfUpdateCommand.php vendor/friendsofphp/php-cs-fixer/src/Console/Command/ListFilesCommand.php vendor/friendsofphp/php-cs-fixer/src/Console/Command/DocumentationCommand.php vendor/friendsofphp/php-cs-fixer/src/Console/Command/WorkerCommand.php vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php

            # 1. copy files to $NESTED_DIRECTORY directory Exclude the scoped/nested directories to prevent rsync from copying in a loop
            -   run: rsync --exclude ecs-build -av * ecs-build --quiet

            # get rector to "rector-local" directory, to avoid downgrading itself in the /vendor
            # downgrade to PHP 7.2
            -   run: mkdir rector-local
            -   run: composer require rector/rector --working-dir rector-local

            # clear the dev files
            -   run: rm -rf tests ecs-build/ecs.php ecs-build/phpstan.neon ecs-build/phpunit.xml ecs-build/.gitignore ecs-build/.editorconfig

            # 2. downgrade via Rector
            -   run: rector-local/vendor/bin/rector process ecs-build/bin ecs-build/config/config.php ecs-build/src ecs-build/vendor --config build/config/config-downgrade.php --ansi --no-diffs

            # 3. prefix classes
            -   run: sh build/build-ecs-scoped.sh ecs-build ecs-prefixed-downgraded

            # 4. lint the code for PHP 7.4 - this must happen here, as setup-php allows only one PHP version switch: https://github.com/shivammathur/setup-php/issues/434
            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 7.2
                    coverage: none
            -   run: mkdir linter-local
            -   run: composer require php-parallel-lint/php-parallel-lint --ansi --working-dir linter-local --dev

            -   run: ../linter-local/vendor/bin/parallel-lint . --exclude vendor/symfony/dependency-injection/Attribute/Autowire.php --exclude vendor/symfony/config/Definition/Dumper/XmlReferenceDumper.php --exclude vendor/symfony/console/Debug/CliRequest.php --exclude vendor/squizlabs/php_codesniffer/tests --exclude vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php --exclude vendor/friendsofphp/php-cs-fixer/src/Console/Command
                working-directory: ecs-prefixed-downgraded

            # 5. copy repository metafiles, composer.json with PHP 7.2, Github Workflows
            -   run: |
                    cp -R build/target-repository/. ecs-prefixed-downgraded
                    cp -R templates ecs-prefixed-downgraded/

            # 6. clone remote repository, so we can push it
            -
                uses: "actions/checkout@v4"
                with:
                    # temporary testing
                    repository: easy-coding-standard/ecs
                    # repository: easy-coding-standard/ecs-deployed
                    path: remote-repository
                    token: ${{ secrets.ACCESS_TOKEN }}

            # remove remote files, to avoid piling up dead code in remote repository
            -   run: rm -rf remote-repository/.github remote-repository/docs remote-repository/config remote-repository/src remote-repository/vendor

            # clear the dev files
            - run: cp -a ecs-prefixed-downgraded/. remote-repository

            # 7, setup git user
            -
                working-directory: remote-repository
                run: |
                    git config user.email "tomas.vot@gmail.com"
                    git config user.name "Tomas Votruba"

            # commit metadata
            -
                name: "Get Git log"
                id: git-log
                run: |
                    echo "log<<EOF" >> $GITHUB_OUTPUT
                    echo "$(git log ${{ github.event.before }}..${{ github.event.after }} --reverse --pretty='https://github.com/easy-coding-standard/ecs-src/commit/%H %s')" >> $GITHUB_OUTPUT
                    echo 'EOF' >> $GITHUB_OUTPUT

            # 8.A publish it to remote repository without tag
            -
                name: "Commit Prefixed - main"
                working-directory: remote-repository
                if: "!startsWith(github.ref, 'refs/tags/')"
                env:
                    INPUT_LOG: ${{ steps.git-log.outputs.log }}
                run: |
                    git remote show origin
                    git add --all
                    git commit -m "Updated ECS to commit ${{ github.event.after }}" -m "$INPUT_LOG"
                    git push --quiet origin main

            # 8.B publish it to remote repository with tag
            -
                name: "Commit Prefixed - tag"
                working-directory: remote-repository
                if: "startsWith(github.ref, 'refs/tags/')"
                env:
                    INPUT_LOG: ${{ steps.git-log.outputs.log }}
                run: |
                    git add --all
                    git commit --allow-empty -m "ECS ${GITHUB_REF#refs/tags/}" -m "$INPUT_LOG"
                    git push --quiet origin main
                    git tag ${GITHUB_REF#refs/tags/} -m "${GITHUB_REF#refs/tags/}"
                    git push --quiet origin ${GITHUB_REF#refs/tags/}
