name: Build Release

on:
    push:
        branches:
            - main
        tags:
            # avoid infinite looping, skip tags that ends with ".72"
            # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-branches
            - '*'

jobs:
    build_release:
        runs-on: ubuntu-latest

        steps:
            -   uses: "actions/checkout@v4"
                with:
                    token: ${{ secrets.ACCESS_TOKEN }}

            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.3
                    coverage: none

            # invoke patches
            -   run: composer install

            # but no dev packages
            -   run: composer update --no-dev

            # remove code-sniffer tests
            -   run: |
                    rm -rf vendor/phpcsstandards/php_codesniffer/tests/
                    rm -rf vendor/phpcsstandards/php_codesniffer/src/Standards/*/Tests/

            # get rector to "rector-local" directory, to avoid downgrading itself in the /vendor
            -   run: mkdir rector-local
            -   run: composer require rector/rector --working-dir rector-local

            # downgrade to PHP 7.2
            -   run: rector-local/vendor/bin/rector process bin config/config.php src vendor --config build/rector-downgrade-php-72.php --ansi

            # verify PHP 7.2 compat
            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 7.2
                    coverage: none

            -   run: composer global require php-parallel-lint/php-parallel-lint --ansi
            -   run: /home/runner/.composer/vendor/bin/parallel-lint src vendor --exclude vendor/symfony/dependency-injection/Attribute/Autowire.php --exclude vendor/symfony/config/Definition/Dumper/XmlReferenceDumper.php --exclude vendor/symfony/console/Debug/CliRequest.php --exclude vendor/squizlabs/php_codesniffer/tests --exclude vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php --exclude vendor/friendsofphp/php-cs-fixer/src/Console/Command

            # clear the dev files
            -   run: rm -rf tests ecs.php phpstan.neon phpunit.xml .gitignore .editorconfig

            # required by scoper
            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.2
                    coverage: none

            -   run: sh prefix-code.sh

            # 6. clone remote repository, so we can push it
            -
                uses: "actions/checkout@v4"
                with:
                    # temporary testing
                    # repository: easy-coding-standard/ecs
                    repository: easy-coding-standard/ecs-deployed
                    path: remote-repository
                    token: ${{ secrets.ACCESS_TOKEN }}

            # copy PHP 7.2 composer + workflows
            -   run: cp -r build/target-repository/. .

            # clear the dev files
            -   run: rm -rf build prefix-code.sh monorepo-builder.php full_ecs_build.sh scoper.php rector.php

            # setup git user
            -

                working-directory: remote-repository
                run: |
                    git config user.email "tomas.vot@gmail.com"
                    git config user.name "Tomas Votruba"

            # commit metadata
            -
                name: "Get Git log"
                id: git-log
                run: |
                    echo "log<<EOF" >> $GITHUB_OUTPUT
                    echo "$(git log ${{ github.event.before }}..${{ github.event.after }} --reverse --pretty='https://github.com/easy-coding-standard/ecs-src/commit/%H %s')" >> $GITHUB_OUTPUT
                    echo 'EOF' >> $GITHUB_OUTPUT

            # 8.A publish it to remote repository without tag
            -
                name: "Commit Prefixed - main"
                working-directory: remote-repository
                if: "!startsWith(github.ref, 'refs/tags/')"
                env:
                    INPUT_LOG: ${{ steps.git-log.outputs.log }}
                run: |
                    git remote show origin
                    git add --all
                    git commit -m "Updated ECS to commit ${{ github.event.after }}" -m "$INPUT_LOG"
                    git push --quiet origin main

            # 8.B publish it to remote repository with tag
            -
                name: "Commit Prefixed - tag"
                working-directory: remote-repository
                if: "startsWith(github.ref, 'refs/tags/')"
                env:
                    INPUT_LOG: ${{ steps.git-log.outputs.log }}
                run: |
                    git add --all
                    git commit --allow-empty -m "ECS ${GITHUB_REF#refs/tags/}" -m "$INPUT_LOG"
                    git push --quiet origin main
                    git tag ${GITHUB_REF#refs/tags/} -m "${GITHUB_REF#refs/tags/}"
                    git push --quiet origin ${GITHUB_REF#refs/tags/}
